#!/usr/bin/env bash

error() { echo "$@" >&2; exit 1; }
success() { echo $@; exit 0; }

if [ ! -d "$HOME/.nvm" ] || [ ! -s "$HOME/.nvm/nvm.sh" ]
then
    export NVM_DIR="$HOME/.nvm" && (
        git clone https://github.com/nvm-sh/nvm.git "$NVM_DIR"
        cd "$NVM_DIR"
        git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
    ) && \. "$NVM_DIR/nvm.sh" && success "nvm installed"
else
    (
        cd "$NVM_DIR"
        git fetch --tags origin
        git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
    ) && \. "$NVM_DIR/nvm.sh" && success "nvm updated"
fi

source "$HOME/.nvm/nvm.sh"

current_version="$(nvm version)"
latest_version="$(nvm version-remote)"

if [ "${current_version}" == "${latest_version}" ]
then
    success "Already on latest version"
fi

nvm install-latest-npm || error "Failed to install latest npm"
nvm install "${latest_version}" || error "Failed to install latest node version ${latest_version}"
nvm use "${latest_version}" || error "Failed to switch node to version ${latest_version}"
nvm alias default "${latest_version}" || error "Failed to set new version ${latest_version} as default"
nvm uninstall "${current_version}" || error "Failed to uninstall previous version ${current_version}"
