#!/usr/bin/env bash

function include_path
{
    while [ $# -gt 0 ]
    do
        grep -qv "$(readlink -f "${1}")" <<< "${PATH}" && export PATH="$(readlink -f "${1}")${PATH:+:}${PATH}"
        shift
    done
}

function include_link_path
{
    while [ $# -gt 0 ]
    do
        grep -qv "${1}" <<< "${PATH}" && export PATH="${1}${PATH:+:}${PATH}"
        shift
    done
}

