#!/usr/bin/env bash

includepath() {
    local target_dir
    local rst="\033[0m"
    local red="\033[1;31m"
    local grn="\033[1;32m"

    if [ "$#" -eq 1 ]
    then
        target_dir="$(readlink -f "$1")"
    else
        target_dir="$PWD"
    fi

    if grep -vq "$target_dir" <<< "$PATH" && [ -d "$target_dir/bin" ]
    then
        export PATH="${target_dir}/bin${PATH:+:}${PATH}"
        echo -e "${red}PATH += ${rst}${target_dir}${grn}/bin${rst}"
    fi

    if grep -vq "$target_dir" <<< "$LD_LIBRARY_PATH" && [ -d "$target_dir/lib" ]
    then
        export LD_LIBRARY_PATH="${target_dir}/lib${LD_LIBRARY_PATH:+:}${LD_LIBRARY_PATH}"
        echo -e "${red}LD_LIBRARY_PATH += ${rst}${target_dir}${grn}/lib${rst}"
    fi
}
