#!/usr/bin/env bash

function include_path
{
    local directory_path
    local directory_name

    while [ $# -gt 0 ]
    do
        directory_path="$(readlink -f "${1}")"
        directory_name="$(basename "${directory_path}")"

        # ignore non-existing paths to make this function functional across different systems
        if ! [ -e "${directory_path}" ]
        then
            shift
            continue
        # path is only meaningful when directory not anything else
        elif ! [ -d "${directory_path}" ]
        then
            echo "${0}: path ${directory_path} is not a directory!" >&2 && shift && continue
        fi

        # directory containing binaries are prepended to PATH
        if [ "${directory_name}" == "bin" ]
        then
            # avoid duplication
            if grep -qvw "${directory_path}" <<< "${PATH}"
            then
                export PATH="${directory_path}${PATH:+:}${PATH}"
            fi
        # directory containing libraries are prepended to LD_LIBRARY_PATH
        elif [ "${directory_name}" == "lib" ] || [ "${directory_name}" == "lib64" ]
        then
            # avoid duplication
            if grep -qvw "${directory_path}" <<< "${LD_LIBRARY_PATH}"
            then
                export LD_LIBRARY_PATH="${directory_path}${LD_LIBRARY_PATH:+:}${LD_LIBRARY_PATH}"
            fi
        # same behavior when the path itself is not bin or lib but contains any of them
        elif [ -d "${directory_path}/bin" ] || [ -d "${directory_path}/lib" ] || [ -d "${directory_path}/lib64" ]
        then
            if [ -d "${directory_path}/bin" ]
            then
                # avoid duplication
                if grep -qvw "${directory_path}/bin" <<< "${PATH}"
                then
                    export PATH="${directory_path}/bin${PATH:+:}${PATH}"
                fi
            fi

            if [ -d "${directory_path}/lib" ]
            then
                # avoid duplication
                if grep -qvw "${directory_path}/lib" <<< "${LD_LIBRARY_PATH}"
                then
                    export LD_LIBRARY_PATH="${directory_path}/lib${LD_LIBRARY_PATH:+:}${LD_LIBRARY_PATH}"
                fi
            fi

            if [ -d "${directory_path}/lib64" ]
            then
                # avoid duplication
                if grep -qvw "${directory_path}/lib64" <<< "${LD_LIBRARY_PATH}"
                then
                    export LD_LIBRARY_PATH="${directory_path}/lib64${LD_LIBRARY_PATH:+:}${LD_LIBRARY_PATH}"
                fi
            fi
        fi

        if find "${directory_path}" -maxdepth 1 -mindepth 1 -type f -executable | grep -q .
        then
            export PATH="${directory_path}${PATH:+:}${PATH}"
        fi

        shift
    done
}
