#!/usr/bin/env bash

# copy and paste this function in your project

is_in_range() {
    local value="$1"
    local min="$2"
    local max="$3"

    [ "$value" -ge "$min" ] && [ "$value" -le "$max" ] && return 0
    return 1
}

