#!/usr/bin/env bash

# Recursively make destination directory, then move into it.
#
# This tiny shell function checks destination existance, and
# make(1) it in case of absence.
# Then uses pushd(1) to change current working directory to it.
#
# Note that previous working directory will be remembered so that
# popd(1) can be used to move working directory back into it.
#
function cdir {
    destination="$1"
    [ -d "$destination" ] || mkdir --parents "$destination"
    pushd "$destination" >/dev/null || exit 1
}

