#!/usr/bin/env bash

# Copy content to clipboard as is.
# When argument given, will be read as file.
# When no arguments found, read from standard input.
if ! command -v xclip &>/dev/null
then
    echo "$(tput setaf 1)xclip is not installed$(tput sgr0)" >&2
    exit 1
elif [ $# -eq 0 ] 
then
    # read from standard input
    xclip -sel clip < /dev/stdin
else
    # read from given file
    xclip -sel clip < "$1"
fi

