#!/usr/bin/env bash

# Move to a temporary directory and remember previous directory.
# popd(1) can be used to go back to previous directory.
function ctemp {
    case "$1" in
        -f|--file) xdg-open $(mktemp) ;;
        -h|--help) echo -e "$0\n\t-f\tfile" ;;
        *) pushd $(mktemp -d) >/dev/null ;;
    esac
}

# Redirect parameters into preceeding function. This is done to
# make all aliases and functions behave similarly as commands.
ctemp $1

