#!/usr/bin/env bash

function genesis_encode_uri()
{
    local keyword="$1"
    local encoded
    local character
    local occurence

    for index in $(seq 0 $((${#keyword} - 1)) )
    do
        character=${keyword:$index:1}

        case "${character}" in
            [-_.~a-zA-Z0-9]) occurence="${character}" ;;
            *) occurence=$(printf '%%%02x' "'${character}") ;;
        esac

        encoded="${encoded}${occurence}"
    done

    echo "${encoded}"
}

function genesis_generate_uri()
{
    local keyword
    local uri
    local filters

    keyword="$(genesis_encode_uri "$1")"
    uri="http://libgen.is/search.php?req=${keyword}"
    filters="res=100&phrase=1&view=detailed&column=def&sort=year&sortmode=DESC"

    echo "${uri}&${filters}"
}

function genesis()
{
    # user should give at least one word in order to attemp a query
    [ $# -eq 0 ] && echo "usage: ${0##*/} <query string>" && exit 1

    # automatically open link by user's default browser
    xdg-open "$(genesis_generate_uri "$*")"
}
