#!/usr/bin/env bash

declare -a available_maintainers

for maintainer in cmake llvm node plantuml
do
    maintainer="${maintainer}-maintenance"
    if command -v $maintainer &>/dev/null
    then
        available_maintainers+=( "$maintainer" )
    fi
done

declare -a selected_maintainers

select maintainer in all "${available_maintainers[@]}"
do
    selected_maintainers+=( "$maintainer" )
done

if grep -q all <<< "${selected_maintainers[*]}"
then
    selected_maintainers=( "${available_maintainers[@]}" )
fi

for maintainer in "${selected_maintainers[@]}"
do
    echo -e "\033[1;33m${maintainer%-*}\033[0m"
    "$maintainer"
done
