#!/usr/bin/env bash

declare -a available_maintainers
declare -A update_report

for maintainer in cmake clang node plantuml
do
    maintainer="${maintainer}-maintenance"
    if command -v $maintainer &>/dev/null
    then
        available_maintainers+=( "$maintainer" )
    fi
done

declare -a selected_maintainers

select maintainer in all "${available_maintainers[@]}"
do
    selected_maintainers+=( "$maintainer" )
done

if grep -q all <<< "${selected_maintainers[*]}"
then
    selected_maintainers=( "${available_maintainers[@]}" )
fi

for maintainer in "${selected_maintainers[@]}"
do
    echo "${maintainer%-*}"
    for package in "$(${maintainer%-*} --version | grep -oE '\w+?\s?(version)?\s?\w+\.\w+\.\w+')"
    do
        echo "$package"
        update_report["${package%% *}"]="${package##* }"
    done

    echo -e "\033[1;33m${maintainer%-*}\033[0m"
    "$maintainer"

    for package in "$(${maintainer%-*} --version | grep -oE '\w+ version \w+.\w+.\w+')"
    do
        update_report["${package%% *}"]+=" => ${package##* }"
    done
done

echo -e "\033[1;35mUpdate Report\033[0m"
for package in "${!update_report[@]}"
do
    echo -e "\033[1;34m${package,,}: \033[1;33m${update_report[$package]}\033[0m"
done
